Update epr-build-pipeline.yaml

diff --git a/epr-build-pipeline.yaml b/epr-build-pipeline.yaml
--- a/epr-build-pipeline.yaml
+++ b/epr-build-pipeline.yaml
@@ -1,175 +1,201 @@
 parameters:
-- name: solutionFolder
-  type: string
-  default: 'src'
-- name: projectFolder
-  type: string
-- name: testProjectFolder
-  type: string
-- name: DataFolder
-  type: string
-  default: 'src'
-- name: sonarQubeProjectKey
-  type: string
-- name: sonarQubeProjectName
-  type: string
-- name: runTests
-  type: boolean
-  default: true
-- name: azureSubscription
-  type: string
-- name: acrAzureContainerRegistryName
-  type: string
-- name: acrRepositoryName
-  type: string
-- name: branchName
-  type: string
-- name: runNugetTasks
-  type: boolean
-  default: true
-- name: buildMigrationScript
-  type: boolean
-  default: false
-- name: componentDirectory
-  type: string
-  default: ''
-- name: runOWASPScan
-  type: boolean
-  default: false
-- name: gitleaksFailOnSecretDetection
-  type: boolean
-  default: false
-- name: serviceName
-  type: string
-  default: ''
-- name: sonarqubeInstance
-  type: string
-  default: SonarQube
-- name: dotnetVersion
-  type: string
-  default: 'dotnetVersion6'
-- name: runAutomationTests #will let us toggle automation tests on or off
-  type: boolean
-  default: true
-
-resources:
-  repositories:
-    - repository: AutomationTesting
-      name: RWD-CPR-EPR4P-ADO/epr-playwright-bdd
-      type: git
-      ref: develop-template-fix
+  - name: solutionFolder
+    type: string
+    default: ''
+  - name: sonarQubeProjectKey
+    type: string
+  - name: sonarQubeProjectName
+    type: string
+  - name: runTests
+    type: boolean
+    default: true
+  - name: runNugetTasks
+    type: boolean
+    default: true
+  - name: sonarqubeInstance
+    type: string
+  - name: dotnetVersion
+    type: string
 
 stages:
-  - template: templates/analyse-and-test.yaml
-    parameters:
-      solutionFolder: ${{ parameters.solutionFolder }}
-      sonarQubeProjectKey: ${{ parameters.sonarQubeProjectKey }}
-      sonarQubeProjectName: ${{ parameters.sonarQubeProjectName }}
-      runTests: ${{ parameters.runTests }}
-      runNugetTasks: ${{ parameters.runNugetTasks }}
-      sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
-      dotnetVersion: ${{ parameters.dotnetVersion }}
-
-  - stage: ValidateAndBuild
+  - stage: SonarQube_Analysis
     jobs:
-      - job: RunGitleaksSecretScan
-        displayName: Run Gitleaks Secret Scan
-        dependsOn: ''
-        variables: 
-        - name: commonTemplatesRepoSubDir
-          value: s/CommonTemplates
-        - name: commonTemplatesRepoRoot
-          value: $(Pipeline.Workspace)/${{ variables.commonTemplatesRepoSubDir }}
-        - name: sourceRepoSubDir
-          value: s/source
-        - name: sourceRepoRoot
-          value: $(Pipeline.Workspace)/${{ variables.sourceRepoSubDir }}
+      - job: SDK_Script
+        displayName: 'SDK Script'
         steps:
-          - checkout: CommonTemplates
-            path: ${{ variables.commonTemplatesRepoSubDir }}
-            clean: true
-          - checkout: self
-            path: ${{ variables.sourceRepoSubDir }}
-            fetchDepth: 0
-          - template: templates/gitleaks-scan.yaml
-            parameters:
-              scanLocation: $(sourceRepoRoot)
-              configPath: $(commonTemplatesRepoRoot)/configuration/gitleaks.toml
-              failOnSecretDetection: ${{ parameters.gitleaksFailOnSecretDetection }}
+        - script: |
+            dotnet --list-sdks
+            if [ "${{ parameters.dotnetVersion }}" == "dotnetVersion8" ]; then
+              echo '{"sdk":{"version":"8.0.303","rollForward":"latestFeature","allowPrerelease":false}}' > ${{ parameters.solutionFolder }}/global.json
+              cat ${{ parameters.solutionFolder }}/global.json
+            else
+              echo '{"sdk":{"version":"6.0.424","rollForward":"latestFeature","allowPrerelease":false}}' > ${{ parameters.solutionFolder }}/global.json
+              cat ${{ parameters.solutionFolder }}/global.json
+            fi
 
-      - ${{ if eq(parameters.runOWASPScan, true) }}:
-        - job: RunOWASPTests
-          displayName: Run OWASP Dependency checks
-          steps:
-            - template: templates/owaspcheck.yaml
-              parameters:
-                solutionFolder: ${{ parameters.solutionFolder }}
-                testProjectFolder: ${{ parameters.testProjectFolder }}
-                componentDirectory: ${{ parameters.componentDirectory }}
-
-      - job: BuildAndPushDockerImage
-        displayName: Build and Push Docker Image
+      - job: SQ_Old_Tasks
+        displayName: 'SQ Old Tasks'
+        dependsOn: SDK_Script
         steps:
-          - template: templates/docker.yaml
-            parameters:
-              azureSubscription: ${{ parameters.azureSubscription }}
-              solutionFolder: ${{ parameters.solutionFolder }}
-              projectFolder: ${{ parameters.projectFolder }}
-              azureContainerRegistryName: ${{ parameters.acrAzureContainerRegistryName }}
-              repositoryName: ${{ parameters.acrRepositoryName }}
-              branchName: ${{ parameters.branchName }}
+          - task: SonarQubePrepare@6
+            displayName: 'SonarQube Old Prepare'
+            inputs:
+              SonarQube: 'SonarQube'
+              scannerMode: 'MSBuild'
+              projectKey: '${{parameters.sonarQubeProjectKey}}'
+              projectName: '${{parameters.sonarQubeProjectName}}'
+              extraProperties: sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
 
-      - job: BuildAndPushSQLMigrationDockerImage
-        displayName: Build and Push Docker Image - Migration Script
-        dependsOn: BuildAndPushDockerImage
-        condition: eq('${{parameters.buildMigrationScript}}', true)
-        steps:
-          - template: templates/docker-sql-migration-script.yaml
-            parameters:
-              azureSubscription: ${{ parameters.azureSubscription }}
-              solutionFolder: ${{ parameters.solutionFolder }}
-              projectFolder: ${{ parameters.projectFolder }}
-              DataFolder: ${{ parameters.DataFolder }}
-              azureContainerRegistryName: ${{ parameters.acrAzureContainerRegistryName }}
-              repositoryName: ${{ parameters.acrRepositoryName }}
-              branchName: ${{ parameters.branchName }}
-      
-  - stage: DeployToDev4
-    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
-    jobs:
-      - job: DeployLatestMainDev4
-        displayName: Deploy Latest Main to Dev4
-        steps:
-          - template: templates/deployment.yaml
-            parameters:
-              imageTag: 'main-latest'
-              azureSubscription: ${{ parameters.azureSubscription }}
-              acrName: ${{ parameters.acrAzureContainerRegistryName }}
-              registryName: ${{ parameters.acrRepositoryName }}
-              serviceName: ${{ parameters.serviceName }}
-              targetEnvironment: 'development'
+          - task: NuGetAuthenticate@1
+            displayName: 'Authenticate to NuGet'
+            condition: eq(${{parameters.runNugetTasks}}, true)
 
-      - ${{ if eq(parameters.runAutomationTests, true) }}:
-        - job: RunAutomationTest
-          displayName: DEV4 Automation Testing
-          dependsOn: DeployLatestMainDev4
-          steps:
-            - checkout: AutomationTesting
-            - template: pipelines/automation-testing-template.yml@AutomationTesting
-              parameters:
-                env: 'dev4'
-                tags: '@sit'
+          - task: DotNetCoreCLI@2
+            displayName: 'NuGet Restore'
+            condition: eq(${{parameters.runNugetTasks}}, true)
+            inputs:
+              command: 'restore'
+              projects: '**/*.sln'
+              feedsToUse: 'config'
+              nugetConfigPath: '${{parameters.solutionFolder}}/NuGet.Config'
 
-      
-      - job: RunLatestSQLMigrationDev4
-        displayName: Run latest SQL Migration for Dev4
-        condition: eq('${{parameters.buildMigrationScript}}', true)
-        steps:
-          - template: templates/docker-run-sql-migration.yaml
-            parameters:
-              azureSubscription: ${{ parameters.azureSubscription }}
-              solutionFolder: ${{ parameters.solutionFolder }}
-              projectFolder: ${{ parameters.projectFolder }}
-              azureContainerRegistryName: ${{ parameters.acrAzureContainerRegistryName }}
-              repositoryName: ${{ parameters.acrRepositoryName }}
-              branchName: 'main-latest'
+          - task: DotNetCoreCLI@2
+            displayName: 'Run Build'
+            inputs:
+              command: build
+              projects: '**/*.csproj'
+
+          - task: DotNetCoreCLI@2
+            displayName: 'Run Unit Tests'
+            condition: eq(${{parameters.runTests}}, true)
+            inputs:
+              command: test
+              projects: '**/*[Uu]nit[Tt]ests/*.csproj'
+              arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
+              publishTestResults: true
+
+          - task: SonarQubeAnalyze@6
+            displayName: 'SonarQube Old Analyse'
+            inputs:
+              jdkversion: 'JAVA_HOME_17_X64'
+
+          - task: SonarQubePublish@6
+            displayName: 'SonarQube Old Publish'
+            retryCountOnTaskFailure: 5
+            inputs:
+              SonarQube: 'SonarQube'
+              pollingTimeoutSec: '300'
+              
+      - job: SQ_Upgraded_Tasks
+        displayName: 'SQ Upgraded Tasks'
+        dependsOn: SDK_Script
+        steps:   
+          - task: SonarQubePrepare@6
+            displayName: 'SonarQube Upgraded Prepare'
+            inputs:
+              SonarQube: 'SonarQubeLatest'
+              scannerMode: 'MSBuild'
+              projectKey: '${{parameters.sonarQubeProjectKey}}'
+              projectName: '${{parameters.sonarQubeProjectName}}'
+              extraProperties: sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
+
+          - task: NuGetAuthenticate@1
+            displayName: 'Authenticate to NuGet'
+            condition: eq(${{parameters.runNugetTasks}}, true)
+
+          - task: DotNetCoreCLI@2
+            displayName: 'NuGet Restore'
+            condition: eq(${{parameters.runNugetTasks}}, true)
+            inputs:
+              command: 'restore'
+              projects: '**/*.sln'
+              feedsToUse: 'config'
+              nugetConfigPath: '${{parameters.solutionFolder}}/NuGet.Config'
+
+          - task: DotNetCoreCLI@2
+            displayName: 'Run Build'
+            inputs:
+              command: build
+              projects: '**/*.csproj'
+
+          - task: DotNetCoreCLI@2
+            displayName: 'Run Unit Tests'
+            condition: eq(${{parameters.runTests}}, true)
+            inputs:
+              command: test
+              projects: '**/*[Uu]nit[Tt]ests/*.csproj'
+              arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
+              publishTestResults: true
+
+          - task: SonarQubeAnalyze@6
+            displayName: 'SonarQube Upgraded Analyse'
+            inputs:
+              jdkversion: 'JAVA_HOME_17_X64'
+
+          - task: SonarQubePublish@6
+            displayName: 'SonarQube Upgraded Publish'
+            retryCountOnTaskFailure: 5
+            inputs:
+              SonarQube: 'SonarQubeLatest'
+              pollingTimeoutSec: '300'
+
+          - task: AzureKeyVault@2
+            displayName: 'Obtain SonarQube Token from Keyvault'
+            inputs:
+              azureSubscription: 'AZD-RWD-DEV1'
+              KeyVaultName: 'DEVRWDINFKV1401'
+              SecretsFilter: 'EPRADO-SonarQubeToken'
+
+          - powershell: |
+                if ("$(Build.Reason)" -eq "PullRequest")
+                {
+                  Write-Host "RepoProvider:" $(Build.Repository.Provider)
+                  Switch ("$(Build.Repository.Provider)") {
+                    "TfsGit" { $pullRequestId = "$(System.PullRequest.PullRequestId)" }
+                    "GitHub" { $pullRequestId = "$(System.PullRequest.PullRequestNumber)" }
+                    Default { Write-Host "Build.Repository.Provider '$(Build.Repository.Provider)' was unexpected"; exit 1 }
+                  }
+                  Write-Host "Checking SonarQube results for" ${{parameters.sonarQubeProjectKey}} "from pull request" $pullRequestId
+                  $qualifier = '&pullRequest='+$pullRequestId
+                }
+                else
+                {
+                  $branchName = "$(Build.SourceBranch)".Replace('refs/heads/', '')
+                  Write-Host "Checking SonarQube results for" ${{parameters.sonarQubeProjectKey}} "from branch" $branchName
+                  $escapedBranchName = [system.uri]::EscapeDataString("$branchName")
+                  $qualifier = '&branch='+$escapedBranchName
+                }
+                Switch ("${{parameters.sonarqubeInstance}}") {
+                  "SonarQube" { $instanceUrlPart = "vss-sonarqube.azure.defra.cloud" }
+                  "SonarQubeLatest" {
+                    $sonarQubeApiToken = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("$(EPRADO-SonarQubeToken):"))
+                    $headers = @{
+                      "Authorization" = "Basic $sonarQubeApiToken"
+                      "Accept" = "application/json"
+                    };
+                    $instanceUrlPart = "vss-sonarqube-upgrade.azure.defra.cloud" 
+                  }
+                  Default { Write-Host "parameters.sonarqubeInstance '${{parameters.sonarqubeInstance}}' was unexpected"; exit 1 }
+                }
+                $uri = "https://$instanceUrlPart/api/qualitygates/project_status?projectKey=${{parameters.sonarQubeProjectName}}" + $qualifier
+                Write-Host "SonarQube URI = " $uri
+                try {
+                  $qualityGateStatus = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get;
+                }
+                catch {
+                  Write-Host "ERROR GETTING SONARQUBE STATUS: " $_
+                  exit 0
+                }
+                if ($qualityGateStatus.projectStatus.status -eq "OK") {
+                  Write-Host "Quality Gate Succeeded";
+                  exit 0; # all is good, quit here
+                } else {
+                  Write-Host "##vso[task.logissue type=warning;]Quality Gate failed."
+                  $gateErrors = $qualityGateStatus.projectStatus.conditions | Where-Object {$_.status -eq "ERROR" };
+                  $gateErrors | ConvertTo-Json;
+                  $webUrl = "https://$instanceUrlPart/dashboard?id=${{parameters.sonarQubeProjectName}}" + $qualifier;
+                  Write-Host "SonarQube link (needs OpenVPN)" $webUrl
+                  Write-Host "##[error]Quality Gate failed. Stopping the build."
+                  exit 1 # HARD FAIL
+                }
+            displayName: Check SonarQube Quality Gate
