Refreshed from ADO

diff --git a/templates/docker-run-sql-migration.yaml b/templates/docker-run-sql-migration.yaml
--- a/templates/docker-run-sql-migration.yaml
+++ b/templates/docker-run-sql-migration.yaml
@@ -77,6 +77,7 @@ steps:
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
+        set -e  # Exit immediately on error
         docker images
 
         docker run --rm \
@@ -85,4 +86,12 @@ steps:
           -e USER='$(sqladminu)' \
           -e PASSWORD='$(sqladminp)' \
           -e DATABASE='$(sqlDB)' \
-          '${{parameters.azureContainerRegistryName}}.azurecr.io/${{parameters.repositoryName}}:${{parameters.branchName}}-database-migrations'
+          '${{parameters.azureContainerRegistryName}}.azurecr.io/${{parameters.repositoryName}}:${{parameters.branchName}}-database-migrations' | tee migration_output.log
+
+        # Check for common SQL errors including invalid cursor state
+        if grep -Ei 'error|invalid cursor state|sqlstate 24000' migration_output.log; then
+          echo 'Migration process failed due to SQL error.'
+          exit 1
+        fi
+
+        echo 'Migration completed successfully.'
